In [2]:
import tensorflow as tf
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt

(train_set, test_set), dataset_info = tfds.load('cats_vs_dogs', split=['train[:81%]', 'train[80%:]'], as_supervised=True, with_info=True)

In [3]:
#Get only cat Image

def preprocess(img, label):
    img = tf.image.resize(img, (150, 150))
    img = img / 255.0  # Normalize to [0,1]
    return img, label

train_set = train_set.map(preprocess).batch(32).shuffle(buffer_size=1000).prefetch(buffer_size=tf.data.experimental.AUTOTUNE)

In [30]:
cats_dataset, dogs_dataset = [], []
for images, labels in train_set.take(3):
    for i in range(32):
        if labels[i] == 0:
            cats_dataset.append(tf.expand_dims(images[i], axis=0))
        else:
            dogs_dataset.append(tf.expand_dims(images[i], axis=0))
            

In [27]:
#Load model 
classifier = tf.keras.models.load_model('cats_dogs_classifier.h5')

In [32]:
for i in cats_dataset:
    print(classifier.predict(i))

[[0.97735834 0.02264164]]
[[9.9981278e-01 1.8726458e-04]]
[[0.9108648 0.0891353]]
[[0.9982009  0.00179912]]
[[9.9998188e-01 1.8126913e-05]]
[[0.9162476  0.08375243]]
[[0.9899776  0.01002238]]
[[9.9984252e-01 1.5742499e-04]]
[[0.21056412 0.78943586]]
[[0.90920526 0.09079468]]
[[0.9851399  0.01486015]]
[[9.999993e-01 7.329803e-07]]
[[9.9999964e-01 3.3554329e-07]]
[[9.9904758e-01 9.5240684e-04]]
[[9.9973518e-01 2.6477425e-04]]
[[9.9999642e-01 3.5761107e-06]]
[[9.9939704e-01 6.0294854e-04]]
[[0.9517443 0.0482557]]
[[0.9962035  0.00379649]]
[[0.94577277 0.05422725]]
[[0.9955764  0.00442367]]
[[9.9999988e-01 1.4838103e-07]]
[[0.9964097  0.00359029]]
[[0.73161405 0.2683859 ]]
[[9.9992621e-01 7.3762065e-05]]
[[0.7719328  0.22806723]]
[[1.00000000e+00 1.29098705e-08]]
[[9.9919850e-01 8.0157485e-04]]
[[9.9998569e-01 1.4347011e-05]]
[[9.9951005e-01 4.8994820e-04]]
[[9.9991047e-01 8.9536385e-05]]
[[0.97744614 0.02255381]]
[[9.9998116e-01 1.8888924e-05]]
[[9.9990046e-01 9.9544472e-05]]
[[0.96602196